
import './globals.css'



export const metadata = {
  title: 'Ai ImageGen App',
  description: 'Generated by Maich',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
